# https://taskfile.dev

version: "3"

tasks:
  build:
    cmds:
      - go build -tags="sonic avx" .
  test:
    cmds:
      - go test -tags="sonic avx" ./... # we use sonic here for fast json binding B

  vet:
    cmds:
      - go vet ./...
  race:
    cmds:
      - go test -race -tags="sonic avx" ./...
  tidy:
    cmds:
      - go mod tidy
  update:
    cmds:
      - go get -u ./...
