name: Test
permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  dependency-review:
    name: Dependency review
    runs-on: ubuntu-latest
    concurrency:
      group: ci-dependency-review
      cancel-in-progress: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
      - name: "Dependency Review"
        uses: actions/dependency-review-action@3b139cfc5fae8b618d3eae3675e383bb1769c019 # v4.5.0
        with:
          base-ref: ${{ github.event.pull_request.base.sha || 'main' }}
          head-ref: ${{ github.event.pull_request.head.sha || github.ref }}
  govulncheck:
    name: Go vulnerabilities check
    runs-on: ubuntu-latest
    concurrency:
      group: ci-govulncheck
      cancel-in-progress: true
    steps:
      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
  test:
    name: Test (${{ matrix.os }} / ${{ matrix.go }})
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ci-test-${{ matrix.os }}-${{ matrix.go }}
      cancel-in-progress: true
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: ["1.25"]
    env:
      TEST_BASEPORT: ${{ vars.TEST_BASEPORT }}
      TEST_BASEPORT_SMTP: ${{ vars.TEST_BASEPORT_SMTP }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
      - name: Setup go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: ${{ matrix.go }}
      - name: Run go test
        run: |
          go test -race -shuffle=on ./...
